-- Migration Script: Item-by-Item to Bill-Based Structure
-- This script migrates existing data from the old structure to the new bill-based structure
-- Run this script ONCE to migrate your existing data

-- Step 1: Create new bill header tables
CREATE TABLE IF NOT EXISTS INCOMING_BILLS (
    Bill_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_Number TEXT UNIQUE,
    Date_Received DATE NOT NULL,
    Supplier_Name TEXT NOT NULL,
    Remarks TEXT,
    Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DONATION_BILLS (
    Bill_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_Number TEXT UNIQUE,
    Date_Received DATE NOT NULL,
    Donor_Name TEXT NOT NULL,
    Remarks TEXT,
    Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OUTGOING_BILLS (
    Bill_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_Number TEXT UNIQUE,
    Date_Issued DATE NOT NULL,
    Center_ID INTEGER NOT NULL,
    Officer_Name TEXT NOT NULL,
    Officer_NIC TEXT NOT NULL,
    Remarks TEXT,
    Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Center_ID) REFERENCES CENTERS_MASTER(Center_ID)
);

-- Step 2: Rename old tables to backup (only if not already renamed)
-- These will fail silently if tables already exist, which is fine

-- Step 3: Create new item tables with Bill_ID reference
CREATE TABLE IF NOT EXISTS INCOMING_STOCK (
    GRN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_ID INTEGER NOT NULL,
    Item_ID INTEGER NOT NULL,
    Qty_Received INTEGER NOT NULL CHECK(Qty_Received > 0),
    Item_Remarks TEXT,
    FOREIGN KEY (Bill_ID) REFERENCES INCOMING_BILLS(Bill_ID) ON DELETE CASCADE,
    FOREIGN KEY (Item_ID) REFERENCES ITEMS_MASTER(Item_ID)
);

CREATE TABLE IF NOT EXISTS DONATIONS (
    Donation_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_ID INTEGER NOT NULL,
    Item_ID INTEGER NOT NULL,
    Qty_Received INTEGER NOT NULL CHECK(Qty_Received > 0),
    Item_Remarks TEXT,
    FOREIGN KEY (Bill_ID) REFERENCES DONATION_BILLS(Bill_ID) ON DELETE CASCADE,
    FOREIGN KEY (Item_ID) REFERENCES ITEMS_MASTER(Item_ID)
);

CREATE TABLE IF NOT EXISTS OUTGOING_STOCK (
    Dispatch_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bill_ID INTEGER NOT NULL,
    Item_ID INTEGER NOT NULL,
    Qty_Requested INTEGER NOT NULL CHECK(Qty_Requested > 0),
    Qty_Issued INTEGER NOT NULL CHECK(Qty_Issued >= 0),
    Item_Remarks TEXT,
    FOREIGN KEY (Bill_ID) REFERENCES OUTGOING_BILLS(Bill_ID) ON DELETE CASCADE,
    FOREIGN KEY (Item_ID) REFERENCES ITEMS_MASTER(Item_ID)
);

-- Step 4: Migrate Incoming Stock data
-- Group by date and supplier to create bills
-- Note: Bill numbers will be generated by trigger after migration
INSERT INTO INCOMING_BILLS (Date_Received, Supplier_Name, Remarks, Created_Date)
SELECT 
    Date_Received,
    Supplier_Name,
    NULL as Remarks,
    MIN(Created_Date) as Created_Date
FROM INCOMING_STOCK_OLD
GROUP BY Date_Received, Supplier_Name;

-- Insert items with their corresponding Bill_ID
INSERT INTO INCOMING_STOCK (Bill_ID, Item_ID, Qty_Received, Item_Remarks)
SELECT 
    ib.Bill_ID,
    iso.Item_ID,
    iso.Qty_Received,
    iso.Remarks as Item_Remarks
FROM INCOMING_STOCK_OLD iso
JOIN INCOMING_BILLS ib ON 
    iso.Date_Received = ib.Date_Received AND 
    iso.Supplier_Name = ib.Supplier_Name;

-- Step 5: Migrate Donations data
-- Note: Bill numbers will be generated by trigger after migration
INSERT INTO DONATION_BILLS (Date_Received, Donor_Name, Remarks, Created_Date)
SELECT 
    Date_Received,
    Donor_Name,
    NULL as Remarks,
    MIN(Created_Date) as Created_Date
FROM DONATIONS_OLD
GROUP BY Date_Received, Donor_Name;

INSERT INTO DONATIONS (Bill_ID, Item_ID, Qty_Received, Item_Remarks)
SELECT 
    db.Bill_ID,
    dso.Item_ID,
    dso.Qty_Received,
    dso.Remarks as Item_Remarks
FROM DONATIONS_OLD dso
JOIN DONATION_BILLS db ON 
    dso.Date_Received = db.Date_Received AND 
    dso.Donor_Name = db.Donor_Name;

-- Step 6: Migrate Outgoing Stock data
-- Note: Bill numbers will be generated by trigger after migration
INSERT INTO OUTGOING_BILLS (Date_Issued, Center_ID, Officer_Name, Officer_NIC, Remarks, Created_Date)
SELECT 
    Date_Issued,
    Center_ID,
    Officer_Name,
    Officer_NIC,
    NULL as Remarks,
    MIN(Created_Date) as Created_Date
FROM OUTGOING_STOCK_OLD
GROUP BY Date_Issued, Center_ID, Officer_Name, Officer_NIC;

INSERT INTO OUTGOING_STOCK (Bill_ID, Item_ID, Qty_Requested, Qty_Issued, Item_Remarks)
SELECT 
    ob.Bill_ID,
    oso.Item_ID,
    oso.Qty_Requested,
    oso.Qty_Issued,
    oso.Remarks as Item_Remarks
FROM OUTGOING_STOCK_OLD oso
JOIN OUTGOING_BILLS ob ON 
    oso.Date_Issued = ob.Date_Issued AND 
    oso.Center_ID = ob.Center_ID AND
    oso.Officer_Name = ob.Officer_Name AND
    oso.Officer_NIC = ob.Officer_NIC;

-- Step 6.5: Generate Bill Numbers for migrated bills
UPDATE INCOMING_BILLS 
SET Bill_Number = 'GRN-' || strftime('%Y%m%d', Date_Received) || '-' || 
                  printf('%04d', (SELECT COUNT(*) FROM INCOMING_BILLS ib2 
                                  WHERE ib2.Date_Received = INCOMING_BILLS.Date_Received 
                                  AND ib2.Bill_ID <= INCOMING_BILLS.Bill_ID))
WHERE Bill_Number IS NULL;

UPDATE DONATION_BILLS 
SET Bill_Number = 'DON-' || strftime('%Y%m%d', Date_Received) || '-' || 
                  printf('%04d', (SELECT COUNT(*) FROM DONATION_BILLS db2 
                                  WHERE db2.Date_Received = DONATION_BILLS.Date_Received 
                                  AND db2.Bill_ID <= DONATION_BILLS.Bill_ID))
WHERE Bill_Number IS NULL;

UPDATE OUTGOING_BILLS 
SET Bill_Number = 'DSP-' || strftime('%Y%m%d', Date_Issued) || '-' || 
                  printf('%04d', (SELECT COUNT(*) FROM OUTGOING_BILLS ob2 
                                  WHERE ob2.Date_Issued = OUTGOING_BILLS.Date_Issued 
                                  AND ob2.Bill_ID <= OUTGOING_BILLS.Bill_ID))
WHERE Bill_Number IS NULL;

-- Step 7: Drop old indexes and create new ones
DROP INDEX IF EXISTS idx_incoming_item;
DROP INDEX IF EXISTS idx_incoming_date;
DROP INDEX IF EXISTS idx_donations_item;
DROP INDEX IF EXISTS idx_donations_date;
DROP INDEX IF EXISTS idx_outgoing_item;
DROP INDEX IF EXISTS idx_outgoing_center;
DROP INDEX IF EXISTS idx_outgoing_date;

-- Create new indexes
CREATE INDEX IF NOT EXISTS idx_incoming_bills_date ON INCOMING_BILLS(Date_Received);
CREATE INDEX IF NOT EXISTS idx_incoming_bills_supplier ON INCOMING_BILLS(Supplier_Name);
CREATE INDEX IF NOT EXISTS idx_incoming_stock_bill ON INCOMING_STOCK(Bill_ID);
CREATE INDEX IF NOT EXISTS idx_incoming_stock_item ON INCOMING_STOCK(Item_ID);

CREATE INDEX IF NOT EXISTS idx_donation_bills_date ON DONATION_BILLS(Date_Received);
CREATE INDEX IF NOT EXISTS idx_donation_bills_donor ON DONATION_BILLS(Donor_Name);
CREATE INDEX IF NOT EXISTS idx_donations_bill ON DONATIONS(Bill_ID);
CREATE INDEX IF NOT EXISTS idx_donations_item ON DONATIONS(Item_ID);

CREATE INDEX IF NOT EXISTS idx_outgoing_bills_date ON OUTGOING_BILLS(Date_Issued);
CREATE INDEX IF NOT EXISTS idx_outgoing_bills_center ON OUTGOING_BILLS(Center_ID);
CREATE INDEX IF NOT EXISTS idx_outgoing_stock_bill ON OUTGOING_STOCK(Bill_ID);
CREATE INDEX IF NOT EXISTS idx_outgoing_stock_item ON OUTGOING_STOCK(Item_ID);

-- Step 8: Verify migration (Check row counts)
-- Uncomment these to verify the migration was successful
-- SELECT 'INCOMING_STOCK_OLD Count:' as Label, COUNT(*) as Count FROM INCOMING_STOCK_OLD;
-- SELECT 'INCOMING_STOCK Count:' as Label, COUNT(*) as Count FROM INCOMING_STOCK;
-- SELECT 'DONATIONS_OLD Count:' as Label, COUNT(*) as Count FROM DONATIONS_OLD;
-- SELECT 'DONATIONS Count:' as Label, COUNT(*) as Count FROM DONATIONS;
-- SELECT 'OUTGOING_STOCK_OLD Count:' as Label, COUNT(*) as Count FROM OUTGOING_STOCK_OLD;
-- SELECT 'OUTGOING_STOCK Count:' as Label, COUNT(*) as Count FROM OUTGOING_STOCK;

-- Step 9: After verifying, you can drop the old tables (OPTIONAL - Keep them as backup)
-- DROP TABLE IF EXISTS INCOMING_STOCK_OLD;
-- DROP TABLE IF EXISTS DONATIONS_OLD;
-- DROP TABLE IF EXISTS OUTGOING_STOCK_OLD;
